In [1]:
import numpy as np

chboard = np.zeros((8,8))
chboard[6,0],chboard[6,1],chboard[6,2],chboard[6,3],chboard[6,4],chboard[6,5],chboard[6,6],chboard[6,7] = 1,2,3,4,5,6,7,8 
chboard[7,0],chboard[7,1],chboard[7,2],chboard[7,3],chboard[7,4],chboard[7,5],chboard[7,6],chboard[7,7] = 15,12,13,17,18,14,11,16
chboard[1,0],chboard[1,1],chboard[1,2],chboard[1,3],chboard[1,4],chboard[1,5],chboard[1,6],chboard[1,7] = 21,22,23,24,25,26,27,28
chboard[0,0],chboard[0,1],chboard[0,2],chboard[0,3],chboard[0,4],chboard[0,5],chboard[0,6],chboard[0,7] = 35,32,34,37,38,33,31,36


In [2]:
def uncaplist(chboard,turn): # analyses the board for p1 pieces left, returns a list of p1 pieces left
    p1piecelist = list(range(1,9)) + list(range(11,19)) + list(range(101,109)) + list(range(111,119)) + list(range(121,129)) + list(range(131,139)) + [100]
    p2piecelist = list(range(21,29)) + list(range(31,39)) + list(range(201,209)) + list(range(211,219)) + list(range(221,229)) + list(range(231,239)) + [200]
    pieceremain = []
    if turn == 1: # if player 1
        for rank in chboard:
            for file in rank:
                if file in p1piecelist:
                    pieceremain.append(file)
        return pieceremain
    if turn == 2: # if player 2
        for rank in chboard:
            for file in rank:
                if file in p2piecelist:
                    pieceremain.append(file)
        return pieceremain

def piecelocator(chboard,pieceid): # finds location of piece on the board, returns a list [rank,file]
    indexcount = 0
    for rank in chboard:
        for file in rank:
            if file == pieceid:
                y = indexcount // 8
                x = indexcount - ((indexcount // 8) * 8)
                return [y,x]
            indexcount += 1
    return [99,99] # piece do not exist

def piecetypelist(turn,piecetype): # lists all possible pieceid for player's piecetype
    if turn == 1:
        if piecetype == 'pawn':
            return list(range(1,9))
        elif piecetype == 'knight':
            return [11,12] + list(range(101,109))
        elif piecetype == 'bishop':
            return [13,14] + list(range(111,119))
        elif piecetype == 'rook':
            return [15,16] + list(range(121,129))
        elif piecetype == 'queen':
            return [17] + list(range(131,139))
        elif piecetype == 'king':
            return [18]
        elif piecetype == 'all':
            return list(range(1,9)) + list(range(11,19)) + list(range(101,109)) + list(range(111,119)) + list(range(121,129)) + list(range(131,139)) + [100]
        else:
            return [999] # error: invalid piecetype
    if turn == 2:
        if piecetype == 'pawn':
            return list(range(21,29))
        elif piecetype == 'knight':
            return [31,32] + list(range(201,209))
        elif piecetype == 'bishop':
            return [33,34] + list(range(211,219))
        elif piecetype == 'rook':
            return [35,36] + list(range(221,229))
        elif piecetype == 'queen':
            return [37] + list(range(231,239))
        elif piecetype == 'king':
            return [38]
        elif piecetype == 'all':
            return list(range(21,29)) + list(range(31,39)) + list(range(201,209)) + list(range(211,219)) + list(range(221,229)) + list(range(231,239)) + [200]
        else:
            return [999] # error: invalid piecetype
    else:
        return [999] # error: not turn 1 or 2



In [3]:
def p2pawncheckmove(chboard,pieceid,rank,file): # determine if P1pawn can move or capture or NONE, returns True/False
    pawnlist, pawnpos, pawn1list, pawn1mcount = list(range(21,29)), piecelocator(chboard,pieceid), list(range(1,9)), 0 #pawn1mcount = player 1 pawn move-counter
    if pieceid in pawnlist:
        if (0 <= rank <= 7) and (0 <= file <= 7):
            
            #### EN-PASSANT SCENARIO ####
            if len(movehistlist) != 0:
                p1epcaptured = movehistlist[len(movehistlist)-1] # Potential En-Passe Captured pawn moveset
                if p1epcaptured[0] in pawn1list: # condition: Must be player 1 pawn ####
                    for moveset in movehistlist:
                        if moveset[0] == p1epcaptured[0]:
                            pawn1mcount += 1
                    if pawn1mcount == 1: # condition: Must be first move of player 1 pawn ####
                        if p1epcaptured[2] == 4: # condition: Must be two square movement (rank 6 to rank 4)  ####
                            pieceidpos = piecelocator(chboard,pieceid)
                            if ((pieceidpos[1] - p1epcaptured[3]) == 1) or ((pieceidpos[1] - p1epcaptured[3]) == -1): # condition: player 1 pawn must be right beside player 2's pawn
                                if chboard[p1epcaptured[2]+1][p1epcaptured[3]] == 0: # condition: enpasse position must be unoccupied
                                    if ((p1epcaptured[2]+1) == rank) and (p1epcaptured[3] == file): # If rank & file input matches the allowed en-passe coordinates
                                        return [True, 'ep']            
            
            if 0 > (pawnpos[0] + 1) > 7: # Check if pawn can move forward\
                return [False, 'n'] # Cannot move forward anymore, no point determining move or capture
            else:
                if pawnpos[0] == 1:
                    vertf = [[pawnpos[0]+1,pawnpos[1]],[pawnpos[0]+2,pawnpos[1]]]
                else:
                    vertf = [[pawnpos[0]+1,pawnpos[1]],[99,99]]
                    
            if 0 > (pawnpos[1] - 1) > 7: # Check if RDIAG is possible
                print('Error: Invalid move')
                rdiagf = None
            else:
                rdiagf = [[pawnpos[0]+1,pawnpos[1]+1]]
                    
            if 0 > (pawnpos[1] + 1) > 7:
                print('Error: Invalid move') # Check if LDIAG is possible
                ldiagf = None
            else:
                ldiagf = [[pawnpos[0]+1,pawnpos[1]-1]]
                    
            for i in vertf:
                if i == [rank,file]:
                    if chboard[rank,file] == 0: # MOVE, NEED 0 TO MOVE
                        return [True, 'n']
            for i in rdiagf:
                if i == [rank,file]:
                    if chboard[rank,file] not in piecetypelist(2,'all'): # CAPTURE
                        return [True, 'n']
            for i in ldiagf:
                if i == [rank,file]:
                    if chboard[rank,file] not in piecetypelist(2,'all'): # CAPTURE
                        return [True, 'n']
                    
            return [False, 'n'] # vertf,rdiagf,ldiagf do not exist
        else:
            return [False, 'n'] #rank/turn inout out of range
    else:
        return [False, 'n'] #pieceid not in pawnlist

def p1pawncheckmove(chboard,pieceid,rank,file): # determine if P1pawn can move or capture or NONE, returns True/False
    pawnlist, pawnpos, pawn2list, pawn2mcount = list(range(1,9)), piecelocator(chboard,pieceid), list(range(21,29)), 0 #pawn2mcount = player 2 pawn move-counter
    if pieceid in pawnlist:
        if (0 <= rank <= 7) and (0 <= file <= 7): 
    
            #### EN-PASSANT SCENARIO ####
            if len(movehistlist) != 0:
                p2epcaptured = movehistlist[len(movehistlist)-1] # Potential En-Passe Captured pawn moveset
                if p2epcaptured[0] in pawn2list: # condition: Must be player 2 pawn ####
                    for moveset in movehistlist:
                        if moveset[0] == p2epcaptured[0]:
                            pawn2mcount += 1
                    if pawn2mcount == 1: # condition: Must be first move of player 2 pawn ####
                        if p2epcaptured[2] == 3: # condition: Must be two square movement (rank 1 to rank 3)  ####
                            pieceidpos = piecelocator(chboard,pieceid)
                            if ((pieceidpos[1] - p2epcaptured[3]) == 1) or ((pieceidpos[1] - p2epcaptured[3]) == -1): # condition: player 1 pawn must be right beside player 2's pawn
                                if chboard[p2epcaptured[2]-1][p2epcaptured[3]] == 0: # condition: enpasse position must be unoccupied
                                    if ((p2epcaptured[2]-1) == rank) and (p2epcaptured[3] == file): # If rank & file input matches the allowed en-passe coordinates
                                        return [True, 'ep']
                                
            #### MAIN PAWN MOVEMENT/CAPTURE FUNCTIONS ####                    
            if 0 > (pawnpos[0] - 1) > 7: # Check if pawn can move forward
                return [False, 'n'] # Cannot move forward anymore, no point determining move or capture
            else:
                if pawnpos[0] == 6:
                    vertf = [[pawnpos[0]-1,pawnpos[1]],[pawnpos[0]-2,pawnpos[1]]]
                else:
                    vertf = [[pawnpos[0]-1,pawnpos[1]],[99,99]]
                    
            if 0 > (pawnpos[1] - 1) > 7: # Check if RDIAG is possible
                print('Error: Invalid move')
                rdiagf = None
            else:
                rdiagf = [[pawnpos[0]-1,pawnpos[1]+1]]
                
            if 0 > (pawnpos[1] + 1) > 7:
                print('Error: Invalid move') # Check if LDIAG is possible
                ldiagf = None
            else:
                ldiagf = [[pawnpos[0]-1,pawnpos[1]-1]]
                    
            for i in vertf:
                if i == [rank,file]:
                    if chboard[rank,file] == 0: # MOVE  DONT HAVE TO BE 0 TO MOVE
                        return [True, 'n']
            for i in rdiagf:
                if i == [rank,file]:
                    if chboard[rank,file] not in piecetypelist(1,'all'): # MOVE
                        return [True, 'n']
            for i in ldiagf:
                if i == [rank,file]:
                    if chboard[rank,file] not in piecetypelist(1,'all'): # MOVE
                        return [True, 'n']
                    
            return [False, 'n'] # vertf,rdiagf,ldiagf do not exist
        else:
            return [False, 'n'] #rank/turn inout out of range
    else:
        return [False, 'n'] #pieceid not in pawnlist

def pawncheckmove(chboard,turn,pieceid,rank,file): # CORE PAWN MOVEMENT/CAPTURE FUNCTION, returns [True/False,p/n]
    if turn == 1:
        if (p1pawncheckmove(chboard,pieceid,rank,file)[0]) and (p1pawncheckmove(chboard,pieceid,rank,file)[1] == 'ep'): # EN-PASSANT!
            return [True, 'ep']
        elif p1pawncheckmove(chboard,pieceid,rank,file)[0]:
            if rank == 0: # PROMOTION!
                return [True, 'p']
            else: # 
                return [True, 'n']
        else: 
            return [p1pawncheckmove(chboard,pieceid,rank,file)[0], 'n']
    elif turn == 2:
        if (p2pawncheckmove(chboard,pieceid,rank,file)[0]) and (p2pawncheckmove(chboard,pieceid,rank,file)[1] == 'ep'): # EN-PASSANT!
            return [True, 'ep']
        elif p2pawncheckmove(chboard,pieceid,rank,file)[0]:
            if rank  == 7: # PROMOTION!
                return [True, 'p']
            else: # 
                return [True, 'n']
        else:
            return [p2pawncheckmove(chboard,pieceid,rank,file)[0], 'n']

def pawnpromote(chboard,rank,file,pmtdpieceid): # promotion of pawn piece to the piece of choice, Inputs old (pawn) and new piece ID, Outputs nothing
    chboard[rank,file] = pmtdpieceid
    return

###### NOTE TO SELF ######
# Run a pawncheckmove before applypawnmove to check if piece can promote, if so, ask player which piece to be promoted to

def applypawnmove(chboard,turn,pieceid,pmtdpieceid,rank,file): # moves pawn piece on chboard to index [rank,file], if promoted, promote
    checkresult = pawncheckmove(chboard,turn,pieceid,rank,file) 
    p2piecelist = list(range(21,29)) + list(range(31,39)) + list(range(201,209)) + list(range(211,219)) + list(range(221,229)) + list(range(231,239)) + [200]
    p1piecelist = list(range(1,9)) + list(range(11,19)) + list(range(101,109)) + list(range(111,119)) + list(range(121,129)) + list(range(131,139)) + [100]
    if checkresult[0] == True: # pawnmove is valid, make pawn move
        if checkresult[1] == 'ep': # pawn does en-passant
            if turn == 1:
                for r in range(0,8): 
                        for f in range(0,8):
                            if pieceid == chboard[r,f]:
                                chboard[r,f] = 0 # remove pawn from old position
                chboard[rank,file] = pieceid # put pawn in new position
                chboard[(rank+1),file] = 0 # remove captured pawn
                return chboard
            elif turn == 2:
                for r in range(0,8): 
                        for f in range(0,8):
                            if pieceid == chboard[r,f]:
                                chboard[r,f] = 0 # remove pawn from old position
                chboard[rank,file] = pieceid # put pawn in new position
                chboard[(rank-1),file] = 0 # remove captured pawn
                return chboard
                
        elif checkresult[1] == 'p': # pawn must promote
            if turn == 2:
                if (pmtdpieceid in p2piecelist) and (pmtdpieceid not in uncaplist(chboard,turn)):
                    for r in range(0,8): 
                        for f in range(0,8):
                            if pieceid == chboard[r,f]:
                                chboard[r,f] = 0 # remove pawn from old position
                    chboard[rank,file] = pieceid # put pawn in new position
                    pawnpromote(chboard,rank,file,pmtdpieceid) # promote pawn
                    return chboard
                else:  
                    return chboard
            elif turn == 1:
                if (pmtdpieceid in p1piecelist) and (pmtdpieceid not in uncaplist(chboard,turn)):
                    for r in range(0,8): 
                        for f in range(0,8):
                            if pieceid == chboard[r,f]:
                                chboard[r,f] = 0 # remove pawn from old position
                    chboard[rank,file] = pieceid # put pawn in new position
                    pawnpromote(chboard,rank,file,pmtdpieceid) # promote pawn
                    return chboard
                else:
                    return chboard
            else:
                return chboard
            
        else: # No promotion, just move/capture
            for r in range(0,8): 
                for f in range(0,8):
                    if pieceid == chboard[r,f]:
                        chboard[r,f] = 0 # remove pawn from old position
            chboard[rank,file] = pieceid # put pawn in new position
            return chboard
    else:
        return chboard # Error: Move is invalid

In [4]:
def knightcheckmove(chboard,turn,pieceid,rank,file): # Checks validity of rank & file of knight movement/capture
    p2knightlist,p1knightlist = list(range(31,33)) + list(range(201,209)), list(range(11,13)) + list(range(101,109))
    knightloc = piecelocator(chboard,pieceid)
    if (pieceid in p1knightlist) or (pieceid in p2knightlist):
        if (0 <= rank <= 7) and (0 <= file <= 7): # within index of the board
            if abs(abs(rank) - abs(knightloc[0])) == 2: # 2 RANKS, 1 FILE
                if abs(abs(file) - abs(knightloc[1])) == 1:
                    if turn == 1: # P2 bishop captures P1 bishop
                        if pieceid in p1knightlist:
                            if chboard[rank,file] == 0:
                                return True
                            elif chboard[rank,file] in uncaplist(chboard,2): 
                                return True
                            else:
                                return False
                    elif turn == 2: # P1 bistop capture P2 bishop
                        if pieceid in p2knightlist:
                            if chboard[rank,file] == 0:
                                return True
                            elif chboard[rank,file] in uncaplist(chboard,1):
                                return True
                            else:
                                return False
                        else:
                            return False
                    else:
                        return False
                else:
                    return False
                        
            elif abs(abs(rank) - abs(knightloc[0])) == 1: # 1 RANKS, 2 FILE
                if abs(abs(file) - abs(knightloc[1])) == 2:
                    if turn == 1: # P2 bishop captures P1 bishop
                        if pieceid in p1knightlist:
                            if chboard[rank,file] == 0:
                                return True
                            elif chboard[rank,file] in uncaplist(chboard,2): 
                                return True
                            else:
                                return False
                    elif turn == 2: # P1 bistop capture P2 bishop
                        if pieceid in p2knightlist:
                            if chboard[rank,file] == 0:
                                return True
                            elif chboard[rank,file] in uncaplist(chboard,1):
                                return True
                            else:
                                return False
                        else:
                            return False
                    else:
                        return False
                else:
                    return False
            else:
                return False
        else:
            return False
    else:
        return False

def applyknightmove(chboard,turn,pieceid,rank,file): # Knight piece on chboard moves to / capture the index [rank,file]
    if knightcheckmove(chboard,turn,pieceid,rank,file):
        chboard[piecelocator(chboard,pieceid)[0],piecelocator(chboard,pieceid)[1]] = 0
        chboard[rank,file] = pieceid
        return chboard
    else:
        return chboard

In [5]:
def bishopcheckmove(chboard,turn,pieceid,rank,file): # Checks validity of rank & file of bishop movement/capture
    p2bishoplist,p1bishoplist = list(range(33,35)) + list(range(211,219)), list(range(13,15)) + list(range(111,119))
    bishoploc,between,rindex,findex = piecelocator(chboard,pieceid),[],0,0
    if (pieceid in p1bishoplist) or (pieceid in p2bishoplist): # condition: this function applies to only bishop pieces
        if (0 <= rank <= 7) and (0 <= file <= 7): # condition: within index of the board
            if abs((bishoploc[0]) - rank) == abs(bishoploc[1] - file): # condition: rank/file index diagonal
                
                # Create 'between' list containing positions in between current piece and selected rank/file
                if abs((bishoploc[0]) - rank) >= 1: # if 'inbetween' has 1 or more positions
                    
                    for inbetween in list(range(abs((bishoploc[0]) - rank) - 1)): # number of 'inbetween' positions is [n-1]
                        if (bishoploc[0] - rank) > 0: # goes up (pos result)(+1) #
                            rindex -= 1
                        else: # goes down (neg result)(-1) #
                            rindex += 1
                        between.append([(bishoploc[0]) + rindex])
                        
                        if (bishoploc[1] - file) > 0: # goes left (pos result)(+1) #
                            findex -= 1
                        else: # goes right (neg result)(-1) #
                            findex += 1
                        between[inbetween].insert(1,(bishoploc[1]) + findex)
                        
                    for bcoord in between: # condition: cannot skip over a player's piece
                        if chboard[bcoord[0],bcoord[1]] != 0:
                            return False
                        
                if turn == 1: # condition: cannot capture friendly piece
                    if pieceid in p1bishoplist:
                        if chboard[rank,file] == 0: # unoccupied position on the board
                            return True
                        elif chboard[rank,file] in uncaplist(chboard,2): # opponent piece occupied on the board
                            return True
                        else:
                            return False # Error: friendly piece
                    else:
                        return False # Error: not p1 bishop piece
                elif turn == 2:
                    if pieceid in p2bishoplist:
                        if chboard[rank,file] == 0: # unoccupied position on the board
                            return True
                        elif chboard[rank,file] in uncaplist(chboard,1): # opponent piece occupied on the board
                            return True
                        else:
                            return False # Error: friendly piece
                    else:
                        return False # Error: not p2 bishop piece
                else:
                    return False # Error: not turn 1 or 2
            else:
                return False # Error: not diagonal
        else:
            return False # Error: index out of range
    else:
        return False # Error: pieceid not bishop piece
                 
def applybishopmove(chboard,turn,pieceid,rank,file): # Bishop piece on chboard moves to / capture the index [rank,file]
    if bishopcheckmove(chboard,turn,pieceid,rank,file):
        chboard[piecelocator(chboard,pieceid)[0],piecelocator(chboard,pieceid)[1]] = 0
        chboard[rank,file] = pieceid
        return chboard
    else:
        return chboard # if move is not valid, returns unchanged chboard

In [6]:
def rookcheckmove(chboard,turn,pieceid,rank,file): # Checks validity of rank & file of rook movement/capture
    p2rooklist,p1rooklist = list(range(35,37)) + list(range(221,229)), list(range(15,17)) + list(range(121,129))
    rookloc,between,rindex,findex = piecelocator(chboard,pieceid),[],0,0
    if (pieceid in p1rooklist) or (pieceid in p2rooklist): # condition: this function applies to only rook pieces
        if (0 <= rank <= 7) and (0 <= file <= 7): # condition: within index of the board
            if (((abs(rookloc[0]-rank)) != 0) and ((abs(rookloc[1]-file)) == 0)) or (((abs(rookloc[0]-rank)) == 0) and ((abs(rookloc[1]-file)) != 0)):
                
                # Create 'between' list containing positions in between current piece and selected rank/file
                if abs(rookloc[0]-rank) >= 1: # if 'inbetween' has 1 or more positions 
                    for inbetween in list(range(abs((rookloc[0]) - rank) - 1)): # number of 'inbetween' positions is [n-1]
                        if (rookloc[0] - rank) > 0: # goes up (pos result)(+1) #
                                rindex -= 1
                        else: # goes down (neg result)(-1) #
                                rindex += 1
                        between.append([(rookloc[0]) + rindex])
                        between[inbetween].insert(1,(rookloc[1]) + findex)
                        
                elif abs(rookloc[1]-file) >= 1: # if 'inbetween' has 1 or more positions 
                    for inbetween in list(range(abs((rookloc[1]) - file) - 1)): # number of 'inbetween' positions is [n-1]
                        if (rookloc[1] - file) > 0: # goes up (pos result)(+1) #
                            findex -= 1
                        else: # goes down (neg result)(-1) #
                            findex += 1
                        between.append([(rookloc[0]) + rindex])
                        between[inbetween].insert(1,(rookloc[1]) + findex)
                for bcoord in between: # condition: cannot skip over a player's piece
                    if chboard[bcoord[0],bcoord[1]] != 0:
                        return False # Error: skip over player's piece
                
                if turn == 1: # condition: cannot capture friendly piece
                    if pieceid in p1rooklist:
                        if chboard[rank,file] == 0: # unoccupied position on the board
                            return True
                        elif chboard[rank,file] in uncaplist(chboard,2): # opponent piece occupied on the board
                            return True
                        else:
                            return False # Error: friendly piece
                    else:
                        return False # Error: not p1 rook piece
                elif turn == 2:
                    if pieceid in p2rooklist:
                        if chboard[rank,file] == 0: # unoccupied position on the board
                            return True
                        elif chboard[rank,file] in uncaplist(chboard,1): # opponent piece occupied on the board
                            return True
                        else:
                            return False # Error: friendly piece
                    else:
                        return False # Error: not p2 rook piece
                else:
                    return False # Error: not turn 1 or 2
            else:
                return False # Error: not horizontal or vertical movement
        else:
            return False # Error: index out of range
    else:
        return False # Error: pieceid not rook piece

def applyrookmove(chboard,turn,pieceid,rank,file): # Rook piece on chboard moves to / capture the index [rank,file]
    if rookcheckmove(chboard,turn,pieceid,rank,file):
        chboard[piecelocator(chboard,pieceid)[0],piecelocator(chboard,pieceid)[1]] = 0
        chboard[rank,file] = pieceid
        return chboard
    else:
        return chboard # if move is not valid, returns unchanged chboard
            

In [7]:
def queencheckmove(chboard,turn,pieceid,rank,file): # Checks validity of rank & file of queen movement/capture
    p2queenlist,p1queenlist = [37] + list(range(231,239)), [17] + list(range(131,139))
    queenloc,between,rindex,findex = piecelocator(chboard,pieceid),[],0,0
    if (pieceid in p1queenlist) or (pieceid in p2queenlist): # condition: this function applies to only queen pieces
        if (0 <= rank <= 7) and (0 <= file <= 7):
            if (((abs(queenloc[0]-rank)) != 0) and ((abs(queenloc[1]-file)) == 0)) or (((abs(queenloc[0]-rank)) == 0) and ((abs(queenloc[1]-file)) != 0)) or (abs((queenloc[0]) - rank) == abs(queenloc[1] - file)): # Condition: Vertical/Horizontal/Diagonal movement
            
            # Create 'between' list containing positions in between current piece and selected rank/file
                if (((abs(queenloc[0]-rank)) != 0) and ((abs(queenloc[1]-file)) == 0)) or (((abs(queenloc[0]-rank)) == 0) and ((abs(queenloc[1]-file)) != 0)): ## VERTICAL/HORIZONTAL MOVEMENT ##    
                    if abs(queenloc[0]-rank) >= 1: # if 'inbetween' has 1 or more positions 
                        for inbetween in list(range(abs((queenloc[0]) - rank) - 1)): # number of 'inbetween' positions is [n-1]
                            if (queenloc[0] - rank) > 0: # goes up (pos result)(+1) #
                                    rindex -= 1
                            else: # goes down (neg result)(-1) #
                                    rindex += 1
                            between.append([(queenloc[0]) + rindex])
                            between[inbetween].insert(1,(queenloc[1]) + findex)
                        
                    elif abs(queenloc[1]-file) >= 1: # if 'inbetween' has 1 or more positions 
                        for inbetween in list(range(abs((queenloc[1]) - file) - 1)): # number of 'inbetween' positions is [n-1]
                            if (queenloc[1] - file) > 0: # goes up (pos result)(+1) #
                                findex -= 1
                            else: # goes down (neg result)(-1) #
                                findex += 1
                            between.append([(queenloc[0]) + rindex])
                            between[inbetween].insert(1,(queenloc[1]) + findex)
                        
                elif (abs((queenloc[0]) - rank) == abs(queenloc[1] - file)): ## DIAGONAL MOVEMENT ##    
                    for inbetween in list(range(abs((queenloc[0]) - rank) - 1)): # number of 'inbetween' positions is [n-1]
                        if (queenloc[0] - rank) > 0: # goes up (pos result)(+1) #
                            rindex -= 1
                        else: # goes down (neg result)(-1) #
                            rindex += 1
                        between.append([(queenloc[0]) + rindex])
                        
                        if (queenloc[1] - file) > 0: # goes left (pos result)(+1) #
                            findex -= 1
                        else: # goes right (neg result)(-1) #
                            findex += 1
                        between[inbetween].insert(1,(queenloc[1]) + findex) 
                    
                for bcoord in between: # condition: cannot skip over a player's piece
                        if chboard[bcoord[0],bcoord[1]] != 0:
                            return False # Error: skip over player's piece
            
                if turn == 1: # condition: cannot capture friendly piece
                    if pieceid in p1queenlist:
                        if chboard[rank,file] == 0: # unoccupied position on the board
                            return True
                        elif chboard[rank,file] in uncaplist(chboard,2): # opponent piece occupied on the board
                            return True
                        else:
                            return False # Error: friendly piece
                    else:
                        return False # Error: not p1 rook piece
                elif turn == 2: 
                    if pieceid in p2queenlist:
                        if chboard[rank,file] == 0: # unoccupied position on the board
                            return True
                        elif chboard[rank,file] in uncaplist(chboard,1): # opponent piece occupied on the board
                            return True
                        else:
                            return False # Error: friendly piece
                    else:
                        return False # Error: not p2 queen piece
                else:
                    return False # Error: not turn 1 or 2
            else:
                return False # Error: not horizontal or vertical movement
        else:
            return False # Error: index out of range
    else:
        return False # Error: pieceid not queen piece

def applyqueenmove(chboard,turn,pieceid,rank,file): # Queen piece on chboard moves to / capture the index [rank,file]
    if queencheckmove(chboard,turn,pieceid,rank,file):
        chboard[piecelocator(chboard,pieceid)[0],piecelocator(chboard,pieceid)[1]] = 0
        chboard[rank,file] = pieceid
        return chboard
    else:
        return chboard # if move is not valid, returns unchanged chboard

In [8]:
def kingprecheckmove(chboard,turn,pieceid,rank,file): # PRECHECKS validity of rank & file of king movement/capture
    p2kinglist,p1kinglist = [38],[18]
    kingloc,between,rindex,findex = piecelocator(chboard,pieceid),[],0,0
    firstkmovecheck,firstrmovecheck,between = 0,0,[]
    if (pieceid in p1kinglist) or (pieceid in p2kinglist): # condition: this function applies to only king pieces
        if (0 <= rank <= 7) and (0 <= file <= 7):
        
            #### CASTLING ####
            if turn == 1:
                if rank != 7: # turn 1 exists only in rank 7
                    return [False,'n']
                for kmoves in movehistlist: # check if king's first move
                    if (piecetypelist(1,'king') in kmoves):
                        firstkmovecheck = 1
                        break
                if firstkmovecheck == 0:
                    if ([kingloc[0],kingloc[1]+2] == [rank,file]): # KING-SIDE Castle
                        for rmoves in movehistlist: # check if king-side rook's first move
                            if 16 in rmoves:
                                return [False,'n']
                            
                        for ks1file in list(range(kingloc[1]+1,kingloc[1]+3)):
                            between.append([rank,ks1file])
                        for i in between: # check for pieces in between
                            if chboard[i[0],i[1]] != 0:
                                return [False,'n']
                        return [True,'ksc'] # Castle true when between all zeros
                            
                    elif ([kingloc[0],kingloc[1]-2] == [rank,file]): # QUEEN-SIDE Castle
                        for rmoves in movehistlist: # check if king-side rook's first move
                            if 15 in rmoves:
                                return [False,'n']
                            
                        for qs1file in list(range(kingloc[1]-3,kingloc[1])):
                            between.append([rank,qs1file])
                        for i in between: # check for pieces in between
                            if chboard[i[0],i[1]] != 0:
                                return [False,'n']
                        return [True,'qsc'] # Castle true when between all zeros
                            
            if turn == 2:
                if rank != 0: # turn 2 exists only in rank 0
                    return [False,'n']
                for kmoves in movehistlist: # check if king's first move
                    if (piecetypelist(2,'king') in kmoves):
                        firstkmovecheck = 1
                        break
                if firstkmovecheck == 0:
                    if ([kingloc[0],kingloc[1]+2] == [rank,file]): # KING-SIDE Castle
                        for rmoves in movehistlist: # check if king-side rook's first move
                            if 36 in rmoves:
                                return [False,'n']
                            
                        for ks2file in list(range(kingloc[1]+1,kingloc[1]+3)):
                            between.append([rank,ks2file])
                        for i in between: # check for pieces in between
                            if chboard[i[0],i[1]] != 0:
                                return [False,'n']
                        return [True,'ksc'] # Castle true when between all zeros
                            
                    elif ([kingloc[0],kingloc[1]-2] == [rank,file]): # QUEEN-SIDE Castle
                        for rmoves in movehistlist: # check if king-side rook's first move
                            if 35 in rmoves:
                                return [False,'n']  
                            
                        for qs2file in list(range(kingloc[1]-3,kingloc[1])):
                            between.append([rank,qs2file])
                        for i in between: # check for pieces in between
                            if chboard[i[0],i[1]] != 0:
                                return [False,'n']
                        return [True,'qsc'] # Castle true when between all zeros
                            
            #### MOVEMENT/CAPTURE ####        
            if ((abs(kingloc[0] - rank) == 1) and (abs(kingloc[1] - file) == 0)) or (abs(kingloc[0] - rank) == 0) and (abs(kingloc[1] - file) == 1) or (abs((kingloc[0]) - rank) == abs((kingloc[1] - file)) and ((abs((kingloc[0]) - rank) - 1) == 0)): # Condition: move hori/vert/diag one square
                
                if turn == 1: # condition: cannot capture friendly piece
                    if pieceid in p1kinglist:
                        if chboard[rank,file] == 0: # unoccupied position on the board
                            return [True,'n']
                        elif chboard[rank,file] in uncaplist(chboard,2): # opponent piece occupied on the board
                            return [True,'n']
                        else:
                            return [False,'n'] # Error: friendly piece
                    else:
                        return [False,'n'] # Error: not p1 rook piece
                    
                elif turn == 2: 
                    if pieceid in p2kinglist:
                        if chboard[rank,file] == 0: # unoccupied position on the board
                            return [True,'n']
                        elif chboard[rank,file] in uncaplist(chboard,1): # opponent piece occupied on the board
                            return [True,'n']
                        else:
                            return [False,'n'] # Error: friendly piece
                    else:
                        return [False,'n'] # Error: not p2 rook piece
                else:
                    return [False,'n'] # Error: not turn 1 or 2            
            else:
                return [False,'n'] # Error: not hori/vert/diag one square movement
        else:
            return [False,'n'] # Error: index out of range
    else:
        return [False,'n'] # Error: pieceid not king piece
                    

def kingcheckmove(chboard,turn,pieceid,rank,file): # CHECKS for 'check' & 'checkmate' conditions, determines validity of king movement/capture
    kschboard = cloneboard(chboard) # kscboard stands for 'King Simulation CHess Board'
    kingloc = piecelocator(kschboard,pieceid) # king piece's rank/file index
    p2pieces,p1pieces = uncaplist(kschboard,2),uncaplist(kschboard,1)
    castleside = 'o'
    
    if kingprecheckmove(chboard,turn,pieceid,rank,file) == [True,'n']: # Condition: valid rank/file movement index
        kschboard[rank,file],kschboard[kingloc[0],kingloc[1]] = pieceid,0 # move king piece on kschboard
        
        if turn == 1: # Simulate P2 piece movement, see if can capture P1 King
            for piece in p2pieces:
                kschboard = cloneboard(chboard)
                kschboard[rank,file],kschboard[kingloc[0],kingloc[1]] = pieceid,0
                
                if piece in piecetypelist(turn+1,'pawn'): ## PAWN PIECE ##
                    applypawnmove(kschboard,2,piece,200,rank,file)
                    if piecelocator(kschboard,pieceid) == [99,99]: # IF king is captured
                        return [False,'n']
                elif piece in piecetypelist(turn+1,'knight'): # KNIGHT PIECE #
                    applyknightmove(kschboard,2,piece,rank,file)
                    if piecelocator(kschboard,pieceid) == [99,99]: # IF king is captured
                        return [False,'n']       
                elif piece in piecetypelist(turn+1,'bishop'): # BISHOP PIECE #
                    applybishopmove(kschboard,2,piece,rank,file)
                    if piecelocator(kschboard,pieceid) == [99,99]: # IF king is captured
                        return [False,'n']     
                elif piece in piecetypelist(turn+1,'rook'): # ROOK PIECE #
                    applyrookmove(kschboard,2,piece,rank,file)
                    if piecelocator(kschboard,pieceid) == [99,99]: # IF king is captured
                        return [False,'n']        
                elif piece in piecetypelist(turn+1,'queen'): # QUEEN PIECE #
                    applyqueenmove(kschboard,2,piece,rank,file)
                    if piecelocator(kschboard,pieceid) == [99,99]: # IF king is captured
                        return [False,'n']    
                elif piece in piecetypelist(turn+1,'king'): # KING PIECE #
                    if kingprecheckmove(kschboard,turn+1,piece,rank,file) == True:
                        kschboard[piecelocator(kschboard,piece)[0],piecelocator(kschboard,piece)[1]] = 0
                        kschboard[rank,file] = piece
                        if piecelocator(kschboard,pieceid) == [99,99]: # IF king is captured
                            return [False,'n']           
            return [True,'n'] # no P2 piece can capture P1 King
                
        elif turn == 2: # Simulate P1 piece movement, see if can capture P2 King
            for piece in p1pieces:
                kschboard = cloneboard(chboard)
                kschboard[rank,file],kschboard[kingloc[0],kingloc[1]] = pieceid,0
                
                if piece in piecetypelist(turn-1,'pawn'): ## PAWN PIECE ##
                    applypawnmove(kschboard,1,piece,100,rank,file)
                    if piecelocator(kschboard,pieceid) == [99,99]: # IF king is captured
                        return [False,'n']    
                elif piece in piecetypelist(turn-1,'knight'): # KNIGHT PIECE #
                    applyknightmove(kschboard,1,piece,rank,file)
                    if piecelocator(kschboard,pieceid) == [99,99]: # IF king is captured
                        return [False,'n']     
                elif piece in piecetypelist(turn-1,'bishop'): # BISHOP PIECE #
                    applybishopmove(kschboard,1,piece,rank,file)
                    if piecelocator(kschboard,pieceid) == [99,99]: # IF king is captured
                        return [False,'n']        
                elif piece in piecetypelist(turn-1,'rook'): # ROOK PIECE #
                    applyrookmove(kschboard,1,piece,rank,file)
                    if piecelocator(kschboard,pieceid) == [99,99]: # IF king is captured
                        return [False,'n']        
                elif piece in piecetypelist(turn-1,'queen'): # QUEEN PIECE #
                    applyqueenmove(kschboard,1,piece,rank,file)
                    if piecelocator(kschboard,pieceid) == [99,99]: # IF king is captured
                        return [False,'n']        
                elif piece in piecetypelist(turn-1,'king'): # KING PIECE #
                    if kingprecheckmove(kschboard,turn-1,piece,rank,file) == True:
                        kschboard[piecelocator(kschboard,piece)[0],piecelocator(kschboard,piece)[1]] = 0
                        kschboard[rank,file] = piece
                        if piecelocator(kschboard,pieceid) == [99,99]: # IF king is captured
                            return [False,'n']                
            return [True,'n'] # no P2 piece can capture P1 King
        else:
            return False # Error: not turn 1 or 2
        
    elif (kingprecheckmove(chboard,turn,pieceid,rank,file) == [True,'ksc']) or (kingprecheckmove(chboard,turn,pieceid,rank,file) == [True,'qsc']): # Condition: valid rank/file movement index
        if turn == 1: # P1 CASTLE
            for piece in p2pieces:
                if kingprecheckmove(chboard,turn,pieceid,rank,file) == [True,'ksc']: # P1 KING-SIDE CASTLE
                    kschboard,castleside = cloneboard(chboard),'k'
                    kschboard[rank,file],kschboard[kingloc[0],kingloc[1]] = pieceid,0
                    kschboard[piecelocator(kschboard,16)[0],piecelocator(kschboard,16)[1]],kschboard[rank,file-1] = 0,16
                elif kingprecheckmove(chboard,turn,pieceid,rank,file) == [True,'qsc']: # P1 KING-SIDE CASTLE
                    kschboard,castleside = cloneboard(chboard),'q'
                    kschboard[rank,file],kschboard[kingloc[0],kingloc[1]] = pieceid,0
                    kschboard[piecelocator(kschboard,15)[0],piecelocator(kschboard,15)[1]],kschboard[rank,file+1] = 0,15             
                    
                if piece in piecetypelist(turn+1,'pawn'): ## PAWN PIECE ##
                    applypawnmove(kschboard,2,piece,200,rank,file)
                    if piecelocator(kschboard,pieceid) == [99,99]: # IF king is captured
                        return [False,'n']
                elif piece in piecetypelist(turn+1,'knight'): # KNIGHT PIECE #
                    applyknightmove(kschboard,2,piece,rank,file)
                    if piecelocator(kschboard,pieceid) == [99,99]: # IF king is captured
                        return [False,'n']       
                elif piece in piecetypelist(turn+1,'bishop'): # BISHOP PIECE #
                    applybishopmove(kschboard,2,piece,rank,file)
                    if piecelocator(kschboard,pieceid) == [99,99]: # IF king is captured
                        return [False,'n']     
                elif piece in piecetypelist(turn+1,'rook'): # ROOK PIECE #
                    applyrookmove(kschboard,2,piece,rank,file)
                    if piecelocator(kschboard,pieceid) == [99,99]: # IF king is captured
                        return [False,'n']        
                elif piece in piecetypelist(turn+1,'queen'): # QUEEN PIECE #
                    applyqueenmove(kschboard,2,piece,rank,file)
                    if piecelocator(kschboard,pieceid) == [99,99]: # IF king is captured
                        return [False,'n']    
                elif piece in piecetypelist(turn+1,'king'): # KING PIECE #
                    if kingprecheckmove(kschboard,turn+1,piece,rank,file) == True:
                        kschboard[piecelocator(kschboard,piece)[0],piecelocator(kschboard,piece)[1]] = 0
                        kschboard[rank,file] = piece
                        if piecelocator(kschboard,pieceid) == [99,99]: # IF king is captured
                            return [False,'n']
                        
            if castleside == 'k':
                return [True,'k'] # Valid King-Side castle
            elif castleside == 'q':
                return [True,'q'] # Valid Queen-Side castle
            
        elif turn == 2: # P2 CASTLE
            for piece in p1pieces:
                if kingprecheckmove(chboard,turn,pieceid,rank,file) == [True,'ksc']: # P1 KING-SIDE CASTLE
                    kschboard,castleside = cloneboard(chboard),'k'
                    kschboard[rank,file],kschboard[kingloc[0],kingloc[1]] = pieceid,0
                    kschboard[piecelocator(kschboard,36)[0],piecelocator(kschboard,36)[1]],kschboard[rank,file-1] = 0,36
                elif kingprecheckmove(chboard,turn,pieceid,rank,file) == [True,'qsc']: # P1 KING-SIDE CASTLE
                    kschboard,castleside = cloneboard(chboard),'q'
                    kschboard[rank,file],kschboard[kingloc[0],kingloc[1]] = pieceid,0
                    kschboard[piecelocator(kschboard,35)[0],piecelocator(kschboard,35)[1]],kschboard[rank,file+1] = 0,35    

                if piece in piecetypelist(turn-1,'pawn'): ## PAWN PIECE ##
                    applypawnmove(kschboard,2,piece,200,rank,file)
                    if piecelocator(kschboard,pieceid) == [99,99]: # IF king is captured
                        return [False,'n']
                elif piece in piecetypelist(turn-1,'knight'): # KNIGHT PIECE #
                    applyknightmove(kschboard,2,piece,rank,file)
                    if piecelocator(kschboard,pieceid) == [99,99]: # IF king is captured
                        return [False,'n']       
                elif piece in piecetypelist(turn-1,'bishop'): # BISHOP PIECE #
                    applybishopmove(kschboard,2,piece,rank,file)
                    if piecelocator(kschboard,pieceid) == [99,99]: # IF king is captured
                        return [False,'n']     
                elif piece in piecetypelist(turn-1,'rook'): # ROOK PIECE #
                    applyrookmove(kschboard,2,piece,rank,file)
                    if piecelocator(kschboard,pieceid) == [99,99]: # IF king is captured
                        return [False,'n']        
                elif piece in piecetypelist(turn-1,'queen'): # QUEEN PIECE #
                    applyqueenmove(kschboard,2,piece,rank,file)
                    if piecelocator(kschboard,pieceid) == [99,99]: # IF king is captured
                        return [False,'n']    
                elif piece in piecetypelist(turn-1,'king'): # KING PIECE #
                    if kingprecheckmove(kschboard,turn-1,piece,rank,file) == True:
                        kschboard[piecelocator(kschboard,piece)[0],piecelocator(kschboard,piece)[1]] = 0
                        kschboard[rank,file] = piece
                        if piecelocator(kschboard,pieceid) == [99,99]: # IF king is captured
                            return [False,'n']
                        
            if castleside == 'k':
                return [True,'k'] # Valid King-Side castle
            elif castleside == 'q':
                return [True,'q'] # Valid Queen-Side castle
            
        else:
            return [False,'n'] # Error: not turn 1 or 2
    else:
        return [False,'n'] # Error: kingprecheckmove failed
                        

def applykingmove(chboard,turn,pieceid,rank,file): # King piece on chboard moves to / capture the index [rank,file]    
    kingloc = piecelocator(chboard,pieceid)
    if kingcheckmove(chboard,turn,pieceid,rank,file) == [True,'n']: # MOVEMENT/CAPTURE
        chboard[piecelocator(chboard,pieceid)[0],piecelocator(chboard,pieceid)[1]] = 0
        chboard[rank,file] = pieceid
        return chboard
    elif turn == 1: # CASTLE
        if kingcheckmove(chboard,turn,pieceid,rank,file) == [True,'k']:
            chboard[rank,file],chboard[kingloc[0],kingloc[1]] = pieceid,0
            chboard[piecelocator(chboard,16)[0],piecelocator(chboard,16)[1]],chboard[rank,file-1] = 0,16
            return chboard
        elif kingcheckmove(chboard,turn,pieceid,rank,file) == [True,'q']:
            chboard[rank,file],chboard[kingloc[0],kingloc[1]] = pieceid,0
            chboard[piecelocator(chboard,15)[0],piecelocator(chboard,15)[1]],chboard[rank,file+1] = 0,15
            return chboard
        else:
            return chboard
    elif turn == 2: # CASTLE
        if kingcheckmove(chboard,turn,pieceid,rank,file) == [True,'k']:
            chboard[rank,file],chboard[kingloc[0],kingloc[1]] = pieceid,0
            chboard[piecelocator(chboard,36)[0],piecelocator(chboard,36)[1]],chboard[rank,file-1] = 0,36
            return chboard
        elif kingcheckmove(chboard,turn,pieceid,rank,file) == [True,'q']:
            chboard[rank,file],chboard[kingloc[0],kingloc[1]] = pieceid,0
            chboard[piecelocator(chboard,35)[0],piecelocator(chboard,35)[1]],chboard[rank,file+1] = 0,35
            return chboard
        else:
            return chboard
    else:
        return chboard # if move is not valid, returns unchanged chboard

In [9]:
def cloneboard(chboard): # copies chboard onto a tempboard
    tempboard = np.zeros((8,8))
    ranks,files = chboard.shape[0],chboard.shape[1]
    tempboard = np.zeros((ranks,files))
    for rrank in range(ranks):
        for ffile in range(files):
            tempboard[rrank,ffile] = chboard[rrank,ffile]
    return tempboard
        
def movehistory(chboard,tempboard,movehistlist): # Modifies a list by adding new moves
    manalysis = [] # FOR CASTLING and EN PASSANT (-1 pawn piece), both chboard is ALWAYS O!
    captured,moved = 'o',0 # captured to determine any piece captured, moved to determine pieceid moved
    rin,fin = -1,-1 # rank index, file index
    staticboard = np.zeros((8,8))
    staticboard[6,0],staticboard[6,1],staticboard[6,2],staticboard[6,3],staticboard[6,4],staticboard[6,5],staticboard[6,6],staticboard[6,7] = 1,2,3,4,5,6,7,8
    staticboard[7,0],staticboard[7,1],staticboard[7,2],staticboard[7,3],staticboard[7,4],staticboard[7,5],staticboard[7,6],staticboard[7,7] = 15,12,13,17,18,14,11,16
    staticboard[1,0],staticboard[1,1],staticboard[1,2],staticboard[1,3],staticboard[1,4],staticboard[1,5],staticboard[1,6],staticboard[1,7] = 21,22,23,24,25,26,27,28
    staticboard[0,0],staticboard[0,1],staticboard[0,2],staticboard[0,3],staticboard[0,4],staticboard[0,5],staticboard[0,6],staticboard[0,7] = 35,32,34,37,38,33,31,36
    
    for rank in list(range(0,8)): # chboard is current board after player moved
        for file in list(range(0,8)):
            if chboard[rank,file] != tempboard[rank,file]: # tempboard should always be 1 turn BEHIND chboard!
                manalysis.append([tempboard[rank,file],chboard[rank,file],[rank,file]]) # append [tp,chp,[rank,file]]
    chpiececount,tpiececount = np.count_nonzero(chboard),np.count_nonzero(tempboard)
    if chpiececount != tpiececount: # determine if a piece was captured
        captured = 'x' ######
    else:
        captured = 'o' #####
        
    if len(manalysis) == 4: # CASTLING
        if manalysis[0][2][0] == 7: # When P1 castles
            for i in manalysis: 
                if i[2] == [7,7]: # King side castle (right)
                    movehistlist.append([18,captured,'k','c'])
                    return                            
            for i in manalysis:
                if i[2] == [7,0]: # Queen side castle (left)
                    movehistlist.append([18,captured,'q','c'])
                    return  
        elif manalysis[0][2][0] == 0: # When p2 castles
            for i in manalysis:
                if i[2] == [0,7]: # King side castle (right)
                    movehistlist.append([38,captured,'k','c'])
                    return                            
            for i in manalysis:
                if i[2] == [0,0]: # Queen side castle (left)
                    movehistlist.append([38,captured,'q','c'])
                    return  
                        
    elif len(manalysis) == 3: # EN PASSANT
        if len(uncaplist(tempboard,1)) != len(uncaplist(chboard,1)): # player 1 piece was captured
            for sets in manalysis:
                if sets[1] in list(range(21,29)):
                    moved = sets[1]
                    if (sets[0] == 0) and(moved == sets[1]):
                        rank,file = sets[2][0],sets[2][1]
                        movehistlist.append([moved,captured,rank,file])
                        return
        elif len(uncaplist(tempboard,2)) != len(uncaplist(chboard,2)): # player 2 piece was captured
            for sets in manalysis:
                if sets[1] in list(range(1,9)):
                    moved = sets[1]
                    if (sets[0] == 0) and(moved == sets[1]):
                        rank,file = sets[2][0],sets[2][1]
                        movehistlist.append([moved,captured,rank,file])
                        return
                            
    else: # its a normal move/capture
        if manalysis[0][1] == 0: # if piece moved, chboard will have '0' 
            moved = manalysis[0][0] ##### piece that moved
            rank,file = manalysis[1][2][0],manalysis[1][2][1] ##### rank and file piece moved to
            movehistlist.append([moved,captured,rank,file])
            return 
        elif manalysis[1][1] == 0: # if piece moved, chboard will have '0'
            moved = manalysis[1][0] ##### piece that moved
            rank,file = manalysis[0][2][0],manalysis[0][2][1] ##### rank and file piece moved to
            movehistlist.append([moved,captured,rank,file])
            return 

In [27]:
movehistlist = []

chboard = np.zeros((8,8))
chboard[6,0],chboard[6,1],chboard[6,2],chboard[6,3],chboard[6,4],chboard[6,5],chboard[6,6],chboard[6,7] = 1,2,3,4,5,6,7,8 
chboard[7,0],chboard[7,1],chboard[7,2],chboard[7,3],chboard[7,4],chboard[7,5],chboard[7,6],chboard[7,7] = 15,12,13,17,18,14,11,16
chboard[1,0],chboard[1,1],chboard[1,2],chboard[1,3],chboard[1,4],chboard[1,5],chboard[1,6],chboard[1,7] = 21,22,23,24,25,26,27,28
chboard[0,0],chboard[0,1],chboard[0,2],chboard[0,3],chboard[0,4],chboard[0,5],chboard[0,6],chboard[0,7] = 35,32,34,37,38,33,31,36
print('tchboard: \n',tchboard)

def kingsim(chboard,turn,pieceid,rank,file,movehistlist): # test function for queen MOVEMENT
    tempboard = cloneboard(chboard)
    chboard = applykingmove(chboard,turn,pieceid,rank,file)
    for i in range(8):
        for j in range(8):
            if tempboard[i,j] != chboard[i,j]:
                movehistory(chboard,tempboard,movehistlist)
                return print(chboard,'\n','\n',movehistlist)
    return print(chboard,'\n','\n',movehistlist) # Error 

    

tchboard: 
 [[35. 32. 34. 37. 38. 33. 31. 36.]
 [21. 22. 23. 24. 25. 26. 27. 28.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  2.  3.  4.  5.  6.  7.  8.]
 [15. 12. 13. 17. 18. 14. 11. 16.]]


In [28]:
kingsim(chboard,1,18,7,2,movehistlist)

[[35. 32. 34. 37. 38. 33. 31. 36.]
 [21. 22. 23. 24. 25. 26. 27. 28.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  2.  3.  4.  5.  6.  7.  8.]
 [15. 12. 13. 17. 18. 14. 11. 16.]] 
 
 []
